// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package movie.movie

object MovieProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      movie.movie.Movie,
      movie.movie.MoviePerson,
      movie.movie.AddMovieResponse
    )
  private lazy val ProtoBytes: Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cgttb3ZpZS5wcm90bxIFbW92aWUitAMKBU1vdmllEhcKAmlkGAEgASgJQgfiPwQSAmlkUgJpZBIgCgV0aXRsZRgCIAEoCUIK4
  j8HEgV0aXRsZVIFdGl0bGUSNgoGZ2VucmVzGAMgAygOMhEubW92aWUuTW92aWVHZW5yZUIL4j8IEgZnZW5yZXNSBmdlbnJlcxJAC
  glkaXJlY3RvcnMYBCADKAsyEi5tb3ZpZS5Nb3ZpZVBlcnNvbkIO4j8LEglkaXJlY3RvcnNSCWRpcmVjdG9ycxI6Cgd3cml0ZXJzG
  AUgAygLMhIubW92aWUuTW92aWVQZXJzb25CDOI/CRIHd3JpdGVyc1IHd3JpdGVycxI0CgVzdGFycxgGIAMoCzISLm1vdmllLk1vd
  mllUGVyc29uQgriPwcSBXN0YXJzUgVzdGFycxJDChJ5ZWFyX29mX3Byb2R1Y3Rpb24YByABKAVCFeI/EhIQeWVhck9mUHJvZHVjd
  GlvblIQeWVhck9mUHJvZHVjdGlvbhI/ChBkdXJhdGlvbl9taW51dGVzGAggASgFQhTiPxESD2R1cmF0aW9uTWludXRlc1IPZHVyY
  XRpb25NaW51dGVzImgKC01vdmllUGVyc29uEi0KCmZpcnN0X25hbWUYASABKAlCDuI/CxIJZmlyc3ROYW1lUglmaXJzdE5hbWUSK
  goJbGFzdF9uYW1lGAIgASgJQg3iPwoSCGxhc3ROYW1lUghsYXN0TmFtZSI7ChBBZGRNb3ZpZVJlc3BvbnNlEicKCG1vdmllX2lkG
  AEgASgJQgziPwkSB21vdmllSWRSB21vdmllSWQqawoKTW92aWVHZW5yZRIKCgZBQ1RJT04QABIKCgZDT01FRFkQARIJCgVEUkFNQ
  RACEgoKBkhPUlJPUhADEgoKBlNDSV9GSRAEEgwKCFRIUklMTEVSEAUSBwoDV0FSEAYSCwoHV0VTVEVSThAHMkMKDE1vdmllU2Vyd
  mljZRIzCghBZGRNb3ZpZRIMLm1vdmllLk1vdmllGhcubW92aWUuQWRkTW92aWVSZXNwb25zZSIAYgZwcm90bzM="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, Array(
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}