// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package movie.movie

sealed trait MovieGenre extends _root_.scalapb.GeneratedEnum {
  type EnumType = MovieGenre
  def isAction: _root_.scala.Boolean = false
  def isComedy: _root_.scala.Boolean = false
  def isDrama: _root_.scala.Boolean = false
  def isHorror: _root_.scala.Boolean = false
  def isSciFi: _root_.scala.Boolean = false
  def isThriller: _root_.scala.Boolean = false
  def isWar: _root_.scala.Boolean = false
  def isWestern: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[MovieGenre] = movie.movie.MovieGenre
}

object MovieGenre extends _root_.scalapb.GeneratedEnumCompanion[MovieGenre] {
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[MovieGenre] = this
  @SerialVersionUID(0L)
  case object ACTION extends MovieGenre {
    val value = 0
    val index = 0
    val name = "ACTION"
    override def isAction: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object COMEDY extends MovieGenre {
    val value = 1
    val index = 1
    val name = "COMEDY"
    override def isComedy: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DRAMA extends MovieGenre {
    val value = 2
    val index = 2
    val name = "DRAMA"
    override def isDrama: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object HORROR extends MovieGenre {
    val value = 3
    val index = 3
    val name = "HORROR"
    override def isHorror: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SCI_FI extends MovieGenre {
    val value = 4
    val index = 4
    val name = "SCI_FI"
    override def isSciFi: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object THRILLER extends MovieGenre {
    val value = 5
    val index = 5
    val name = "THRILLER"
    override def isThriller: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object WAR extends MovieGenre {
    val value = 6
    val index = 6
    val name = "WAR"
    override def isWar: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object WESTERN extends MovieGenre {
    val value = 7
    val index = 7
    val name = "WESTERN"
    override def isWestern: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(value: _root_.scala.Int) extends MovieGenre with _root_.scalapb.UnrecognizedEnum
  
  lazy val values = scala.collection.immutable.Seq(ACTION, COMEDY, DRAMA, HORROR, SCI_FI, THRILLER, WAR, WESTERN)
  def fromValue(value: _root_.scala.Int): MovieGenre = value match {
    case 0 => ACTION
    case 1 => COMEDY
    case 2 => DRAMA
    case 3 => HORROR
    case 4 => SCI_FI
    case 5 => THRILLER
    case 6 => WAR
    case 7 => WESTERN
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = MovieProto.javaDescriptor.getEnumTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = MovieProto.scalaDescriptor.enums(0)
}